storefront/articles/urls.py
from django.urls import path 
from django.conf.urls import url 
from articles import views


app_name="articles"
urlpatterns=[
    path('',views.index,name="list"),
    url(r'^(?P<slug>[\w-]+)/$',views.article_detail,name="detail")
]

storefront/playground/urls.py
from django.urls import path 
from . import views 


#URLConf module 
urlpatterns=[
    path('hello/',views.say_hello)
]

storefront/storefront/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings 
from django.conf.urls.static import static 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('playground/',include('playground.urls')),
    path('__debug__/', include('debug_toolbar.urls')),
    path('articles/',include('articles.urls'))

]

 
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 
 

storefront/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateField(auto_now_add=True)
    thumb = models.ImageField(default='article.png', blank=True)


    def __str__(self):
        return self.title
    
    def snippet(self):
        return self.body[:50]+"......"

storefront/playground/models.py
from django.db import models

# Create your models here.

storefront/articles/views.py
from django.shortcuts import render
from .models import Article 
from django.http import HttpResponse
# Create your views here.

def index(request):
    articles=Article.objects.all().order_by('date')
    return render(request,"index.html",{'articles':articles})


def article_detail(request,slug):
    #return HttpResponse(slug)
    article=Article.objects.get(slug=slug)
    return render(request,"article_detail.html",{'article':article})

storefront/playground/views.py
from django.shortcuts import render
from django.http import HttpResponse 


# Create your views here.

def say_hello(request):
    return render(request,'hello.html',{'name':'Lameck Odiwuor'})

storefront/articles/templates/article_detail.html
{% extends "base.html" %}

{% block content %}
<div class="article-detail">
    <div class="article">
     <h2>{{article.title}}</h2>
     <img src="{{article.thumb.url}}"/>
     <p>{{article.body}}</p>
     <p>{{article.date}}</p>
    </div>

</div>
{% endblock %}

storefront/articles/templates/base.html
html>
    <head><title>Blog post</title>
    <link rel="stylesheet" href="/static/styles.css">
    
    </head>
    <body>
        <div class="wrapper">
            <h1><a href="{% url 'articles:list' %}"><img src="/static/article.png"/></a></h1>
            {%block content%}
            {% endblock %}
        </div>
    </body>
    </html>

storefront/articles/templates/index.html
{% extends "base.html"%}
{% block content %}
        <h1>Articles List  </h1>
        <div class ="articles">
            {% for article in articles%}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug%}">{{article.title}}</a></h2>
                <p>{{article.snippet}}</p>
                <p>{{article.date}}</p>

            </div>
             {% endfor%}
        </div>

{% endblock %}

    

storefront/playground/templates/hello.html
<html>
    <head><title>Hello</title></head>
    <body>
        {% if name %}
<h1>Hello {{name}} </h1>
{% else %}
<h1>Hello World</h1>

{% endif %}
    </body>
    </html>
    